### ISSUE TITLE
Request for Dataset Organization Format or Sample Data for the Cervical Cancer Project

### ISSUE THREAD

**Issue by cjjcn** [bittersweet1999/cervical-cancer#6]
I hope this message finds you well. I have been closely following your research and am impressed by the progress.

I am now troubled by the organizational format of the dataset, and it still takes a long time to restore the organizational format of the data from the my_dataset.py file. It would be immensely helpful if you could share the dataset organization format or, if possible, a sample snippet of the dataset to provide clarity on its structure.

Thank you for considering this request. Your contributions to the field and the open-source community are truly appreciated.

**Comment by bittersweet1999** [comment]
Thanks for your attention. Due to the latest findings not yet being published, I will provide you with model guidance from the MICCAI 2023 paper. Please leave me an email, and I will send you a detailed guidance.

**Comment by bittersweet1999** [comment]
[guidance.zip](https://github.com/bittersweet1999/cervical-cancer/files/14855993/guidance.zip)
Or here is the `guidance.zip`, you can download and see it. The latest model link is in the guidance.txt (baidudisk link), or you can try this googledrive link: https://drive.google.com/file/d/1-C_dOecnDoh8Cy26dw62Wa4HuizWLJmm/view?usp=drive_link 
Since there is a limit in file size, so I reduced the number of images in the fold `patient` to 8, in general, it needs at least 50 images.

**Comment by cjjcn** [comment]
OK, I see. Thanks a lot for your generous assistance. Wishing you continued success and smooth progress in your research endeavors.🚀

**Comment by LIUYI-0613** [comment]
您好，很庆幸能够看到您的论文与代码，让我对这个领域学到了新的知识！看了您的指导文件，但是我刚开始学习，没有理清如何准备数据集，并完成训练，可否麻烦您告知我需要准备的数据应该是什么样的，怎样的像素大小，以及测试集与训练集的csv文件我该如何准备？
